name: test run scratch

# Definition when the workflow should run
on:
  # The workflow will run whenever an event happens on a pull request
  pull_request:
    types: [opened, synchronize]

jobs:
  validate_npc:
    runs-on: ubuntu-latest
    steps:
      - name: "Create scratch org"
        uses: forcedotcom/salesforcedx-actions@master
        with:
          args: "org create scratch -d -f config/nonprofit-cloud.json -a npc-org"
