name: test run scratch

# Definition when the workflow should run
on:
  # The workflow will run whenever an event happens on a pull request
  pull_request:
    types: [opened, synchronize]

jobs:
  validate_npc:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code in the pull request
      - name: "Checkout source code"
        uses: actions/checkout@v3
      # Store secret for dev hub
      - name: "Populate auth file with DEVHUB_SFDX_URL secret"
        shell: bash
        run: |
          echo ${{ secrets.DEVHUB_SFDX_URL }} > ./DEVHUB_SFDX_URL.txt
          secretFileSize=$(wc -c "./DEVHUB_SFDX_URL.txt" | awk '{print $1}')
          if [ $secretFileSize == 1 ]; then
              echo "Missing DEVHUB_SFDX_URL secret. Is this workflow running on a fork? You need to setup required secrets.";
              exit 1;
          fi
      # Authenticate dev hub
      - name: "Authenticate Dev Hub"
        run: sf org login sfdx-url -f ./DEVHUB_SFDX_URL.txt -a devhub -d
      # Create a scratch org
      - name: "Create scratch org"
        uses: forcedotcom/salesforcedx-actions@master
        with:
          args: "org create scratch -d -f config/nonprofit-cloud.json -a npc-org"
